name: build

on:
  workflow_call:

jobs:
  build_and_archive:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: dist
          retention-days: 20