name: lint + test

on:
  workflow_call:

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download built application on the previous job
        uses: actions/download-artifact@v2
        with:
          name: application
          path: ./dist
      - run: ls -l
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOTELY_456FD }}'
          channelId: live
          projectId: notely-456fd