name: lint + test

on:
  workflow_call:
    secrets:
      g_token:
        required: true
      firebase_service_account:
        required: true

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download built application on the previous job
        uses: actions/download-artifact@v2
        with:
          name: application
          path: ./dist
      - run: ls -l
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.g_token }}
          firebaseServiceAccount: ${{ secrets.firebase_service_account }}
          channelId: live
          projectId: notely-456fd