name: notely prod Ci/CD(firebase hosting)

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  lint_test:
    uses: XoldpandaX/notely/.github/workflows/lint_test.yml@main

  build_and_archive:
    needs: [lint_test]
    uses: XoldpandaX/notely/.github/workflows/build_and_archive.yml@main

  deploy:
    needs: [build_and_archive]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download built application on the previous job
        uses: actions/download-artifact@v2
        with:
          name: application
          path: ./dist
      - run: ls -l
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOTELY_456FD }}'
          channelId: live
          projectId: notely-456fd
