name: notely prod Ci/CD(firebase hosting)

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  lint_test:
    uses: XoldpandaX/notely/.github/workflows/lint_test.yml@main

  build_and_archive:
    needs: [lint_test]
    uses: XoldpandaX/notely/.github/workflows/build_and_archive.yml@main

  deploy_prod:
    needs: [build_and_archive]
    uses: XoldpandaX/notely/.github/workflows/deploy_prod.yml@main
    secrets:
      g_token: ${{ secrets.GITHUB_TOKEN }}
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOTELY_456FD }}